### PR TITLE
Across blanket communication. 

### PR DESCRIPTION
**Pull request by daphnedemekas**
Only a single bit of information in each direction crossing the blanket

pick one cell behind the blanket; that cell is connected to the seed cell, the other cells are not connected across the blanket 

Each network has two "blanket cells" that have each other as neighbors 
- How do we define the connectivity of the blanket cell within the network? 
- Can they divide or die? What happens if they divide or die? 

* maybe that cell is connected to everyone 
* if seed cell divides then it’s child will also be connected which is not ideal for experimenting 
* then we have to give the ABB the ability to grow 

so a potential way to implement that is symmetric division 

Sensory cell and active cell 

**Markov blanket:
- sensory cell only acts on the generative model 
- active cell is taking what the generative model is saying and giving it to the environment**

### CODE REVIEW

**Comment by lars-sandved** [comment]
I propose that we set this up to have a proper markov blanket as defined by the conditional sparsity. I think this will be important for the dynamics ultimately, but also gives real reason to talk about there being a markov blanket. 

Practically that would mean having a sensory cell (or network of cells) that receive messages from the process network, and send messages to the model network. And an active cell (or network of cells) that receive messages from the model network and send messages to the process network. 

this would be a more accurate setup making it more readily applicable to different situations and give more interesting dynamics.

**Comment by daphnedemekas** [comment]
We now have separation in internal, external, active and sensory networks, and we have a demo showing the signals, efe and stemness values associated with each node over 50 time steps. 
simulation:2-3

**Comment by lars-sandved** [comment]
Very cool - nice work ! 

I think we should also add communication between the active and sensory nodes.
image

**Comment by daphnedemekas** [comment]
Ok, updates from today are we now have 

1) A Markovian system, as before but now with active and sensory cells also interacting and 

2) A NonMarkovian system, which just has internal and external networks that are each connected via one cell connection, as per Adam's model 

Please help me rename these 
simulation:2-3

inactive-simulation:2-3

**Comment by daphnedemekas** [comment]
Also, I'm currently not sure about whether we are waiting for implementation of model precision things to start expecting synchronicity, or if we should be thinking about specific  configurations of B matrices of the external cells for example that might encourage synchronization.. right now they are just deterministic and random. 

Also, active and sensory cells in the markovian system are now learning B as well

**Pull request merged**
